metadata_path: ../data/.../data.csv
out_dir: ../data/.../Segmented/
segmented_metadata_path: ../data/.../Segmented/segmented_data_seg.csv
name_prefix: binhealvalid   # Do not use any hyphen `-` in the prefix. 
img_ext: .tiff
msk_ext: .png
visualize: false